// FontAwesome imports
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

// Specific FontAwesome icons
import {
  faLayerGroup,
  faCircleChevronDown,
  faFileLines,
  faBox,
  faChartSimple,
  faCircleChevronUp,
  faBars,
  faCircleUser,
  faPlus,
  faEnvelope,
  faUserLock,
  faUser,
  faRightToBracket,
  faWarehouse,
  faBriefcase,
  faSpinner,
  faRightFromBracket,
  faHandHoldingDollar,
  faUserGroup,
  faX,
  faIdBadge,
  faPhone,
  faSave,
  faClose,
  faEdit,
  faTrash,
  faArrowLeft,
  faArrowRight,
  faChevronLeft,
  faChevronRight,
  faAnglesLeft,
  faAnglesRight,
  faRulerCombined,
  faRulerHorizontal,
  faWarning,
  faClipboardList,
  faList,
  faCalendarAlt,
  faScissors,
  faDollar,
  faDollarSign,
  faFilterCircleDollar,
  faCircleDollarToSlot
} from '@fortawesome/free-solid-svg-icons'

// Add icons to the library
library.add(
  faLayerGroup,
  faCircleChevronDown,
  faCircleChevronUp,
  faFileLines,
  faBox,
  faChartSimple,
  faBars,
  faCircleUser,
  faPlus,
  faEnvelope,
  faUserLock,
  faUser,
  faRightToBracket,
  faWarehouse,
  faBriefcase,
  faSpinner,
  faRightFromBracket,
  faHandHoldingDollar,
  faUserGroup,
  faX,
  faIdBadge,
  faEnvelope,
  faPhone,
  faSave,
  faClose,
  faEdit,
  faTrash,
  faArrowLeft,
  faArrowRight,
  faChevronLeft,
  faChevronRight,
  faAnglesLeft,
  faAnglesRight,
  faRulerHorizontal,
  faRulerCombined,
  faWarning,
  faClipboardList,
  faList,
  faCalendarAlt,
  faScissors,
  faCircleDollarToSlot,
)

// Export FontAwesomeIcon to use in main.js
export { FontAwesomeIcon }
